function cfg = autlDefaultConfig()
% autlDefaultConfig
% Default configuration for ontology+AI trajectory generation.

cfg = struct();

cfg.policy = struct(...
    'horizon_s', 8.0, ...
    'dt', 0.1, ...
    'max_xy_speed', 0.8, ...
    'max_z_descent_speed', 0.7, ...
    'min_z_descent_speed', 0.15);

cfg.fusion = struct(...
    'semantic_weight', 0.45, ...
    'ai_weight', 0.55);

cfg.ai = struct(...
    'model_path', fullfile('ai', 'models', 'autl_ai_model_v1.mat'), ...
    'auto_train_if_missing', true, ...
    'feature_names', {{'semantic_risk', 'semantic_safety', 'wind_risk', 'vision_risk', 'alignment_risk', 'relation_density'}});

cfg.validation = struct(...
    'decision_threshold', 0.55);

cfg.risk = struct(...
    'wind_scale', 0.1, ...
    'gust_scale', 0.6, ...
    'vision_err_scale', 0.5);
end
