function summary = AutoLandingMain(varargin)
% AUTOLANDINGMAIN
% MATLAB entrypoint for standard workspace execution.

  defaults = struct( ...
      'mode', 'full', ...
      'num_drones', 1, ...
      'num_landing_pads', 1, ...
      'scenarios_per_worker', 12, ...
      'train_ratio', 0.8, ...
      'val_ratio', 0.2, ...
      'headless', false, ...
      'auto_flight_demo', true, ...
    'drone_spawn_above_pad_m', 0.35, ...
    'landing_pad_size_xy', 2.4, ...
    'demo_takeoff_alt_m', 1.2, ...
    'control_backend', 'mavros');

  if nargin >= 1 && isstruct(varargin{1})
    user_overrides = varargin{1};
    names = fieldnames(user_overrides);
    for i = 1:numel(names)
      defaults.(names{i}) = user_overrides.(names{i});
    end
  end

  summary = AutoLandingMainFull(defaults);
end
