function summary = AutoLandingMain(varargin)
% AUTOLANDINGMAIN
% MATLAB entrypoint for standard workspace execution.

  % Pass through non-struct invocations (e.g. AutoLandingMain('gui')).
  if nargin >= 1 && ~isstruct(varargin{1})
    if (ischar(varargin{1}) || isstring(varargin{1})) && any(strcmpi(strtrim(char(string(varargin{1}))), {'stop', 'cleanup', 'kill'}))
      summary = localStopSimulationStack();
      return;
    end
    summary = AutoLandingMainFull(varargin{:});
    return;
  end

  defaults = struct( ...
      'mode', 'full', ...
      'num_drones', 2, ...
      'num_landing_pads', 2, ...
      'scenarios_per_worker', 200, ...
      'train_ratio', 0.8, ...
      'val_ratio', 0.2, ...
      'headless', false, ...
      'auto_flight_demo', true, ...
    'drone_spawn_above_pad_m', 0.25, ...
    'landing_pad_size_xy', 5.4, ...
    'initial_spawn_x_m', 1.0, ...
    'initial_spawn_y_m', 0.35, ...
    'initial_spawn_z_m', 0.15, ...
    'demo_takeoff_alt_m', 1.2, ...
    'control_backend', 'mavros');

  if nargin >= 1 && isstruct(varargin{1})
    user_overrides = varargin{1};
    names = fieldnames(user_overrides);
    for i = 1:numel(names)
      defaults.(names{i}) = user_overrides.(names{i});
    end
  end

  summary = AutoLandingMainFull(defaults);
end

function summary = localStopSimulationStack()
% Stop Gazebo/SITL/MAVROS stack launched by AutoLandingMain/AutoLandingMainFull.

  cmd = [ ...
      'bash -lc ''set +e; ' ...
      'pkill -TERM -f "gz sim|gzserver|gzclient|ign gazebo|rviz2|rviz|mavros_node|arducopter|sim_vehicle.py|mavproxy.py" >/dev/null 2>&1 || true; ' ...
      'fuser -k 5760/tcp >/dev/null 2>&1 || true; ' ...
      'fuser -k 5762/tcp >/dev/null 2>&1 || true; ' ...
      'fuser -k 14550/udp >/dev/null 2>&1 || true; ' ...
      'sleep 1; ' ...
      'pkill -KILL -f "gz sim|gzserver|gzclient|ign gazebo|rviz2|rviz|mavros_node|arducopter|sim_vehicle.py|mavproxy.py" >/dev/null 2>&1 || true; ' ...
      'exit 0'''];

  [status, out] = system(cmd); %#ok<ASGLU>
  summary = struct('ok', status == 0, 'message', 'Simulation stack stop command executed.');
  fprintf('[AutoLandingMain] %s\n', summary.message);
end
