aruco_node:
  ros__parameters:
    image_topic: /camera
    camera_info_topic: /camera_info
    camera_frame: camera_link
    marker_size: 0.4
    aruco_dictionary_id: DICT_4X4_50
    marker_ids: [23]
